from enum import Enum
from pathlib import Path

from ninja_syntax import Writer

SCRIPTS_DIR = Path(__file__).parent


class BuildType(Enum):
    NORMAL = 1
    DIFFBUILD = 2
    TESTS = 3


def configure(build_type):
    with (SCRIPTS_DIR.parent / "build.ninja").open("w") as f:
        writer = Writer(f, width=120)
        writer.variable("ninja_required_version", "1.5")

        writer.variable("builddir", "build")

        writer.variable("cl", "cl.exe")
        writer.variable(
            "cl_common_flags",
            "/nologo /MT /EHsc /G5 /Gs /GS /DNDEBUG /Zi /I $builddir/autogenerated /I src /I src/pbg3 /I 3rdparty/munit",
        )
        writer.variable("cl_flags", "$cl_common_flags /Od /Oi /Ob1 /Op")
        writer.variable("cl_flags_pbg3", "$cl_common_flags /O2")
        if build_type == BuildType.DIFFBUILD:
            writer.variable("cl_flags", "$cl_flags /DDIFFBUILD")
            writer.variable("cl_flags_pbg3", "$cl_flags /DDIFFBUILD")
        writer.variable("gas", "as.exe")
        writer.variable("rc", "rc.exe")
        writer.variable("link", "link.exe")
        writer.variable(
            "link_flags",
            "/nologo /subsystem:windows /machine:X86 /filealign:4096 /incremental:no",
        )
        writer.variable(
            "link_libs",
            "dxguid.lib d3dx8.lib d3d8.lib dsound.lib winmm.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib",
        )

        writer.variable("msvc_deps_prefix", "Note: including file:")
        writer.rule(
            "cc", "$cl /showIncludes $cl_flags /c $in /Fd$out.pdb /Fo$out", deps="msvc"
        )
        writer.rule(
            "cc_pbg3",
            "$cl /showIncludes $cl_flags_pbg3 /c $in /Fd$out.pdb /Fo$out",
            deps="msvc",
        )
        writer.rule("as", "$gas -o $out $in")
        writer.rule("rc", "$rc /fo $out $in")
        writer.rule(
            "link",
            """cmd /c "for %F in ("$out") do $link $link_flags /out:%F /debug /pdb:%~pdnF.pdb $link_libs $in" """,
        )
        writer.rule(
            "copyicon",
            'python -c "import shutil; import sys; shutil.copyfile(sys.argv[1], sys.argv[2])" $in $out',
        )
        writer.rule(
            "geni18n",
            """python -c "import sys; open(sys.argv[2], 'wb').write(open(sys.argv[1], 'rb').read().decode('utf8').encode('shift_jis'))" $in $out""",
        )

        main_sources = ["main"]
        cxx_sources = [
            "AsciiManager",
            "Chain",
            "FileSystem",
            "Supervisor",
            "GameErrorContext",
            "GameWindow",
            "MidiOutput",
            "SoundPlayer",
            "Stage",
            "AnmManager",
            "GameManager",
            "Rng",
            "utils",
            "zwave",
        ]

        pbg3_sources = [
            "IPbg3Parser",
            "Pbg3Parser",
            "Pbg3Archive",
            "FileAbstraction",
        ]

        munit_sources = ["munit"]

        test_sources = [
            "tests",
            "test_Pbg3Archive",
        ]

        for rule in main_sources + cxx_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "src/" + rule + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
            )

        for rule in pbg3_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc_pbg3",
                "src/pbg3/" + rule + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
            )

        for rule in munit_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "3rdparty/munit/" + rule + ".c",
            )

        for rule in test_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "tests/" + rule + ".cpp",
            )

        writer.build("$builddir/globals.obj", "as", inputs="src/globals.asm")
        writer.build("$builddir/autogenerated/i18n.hpp", "geni18n", "src/i18n.tpl")
        writer.build("$builddir/icon.ico", "copyicon", "resources/placeholder.ico")
        writer.build(
            "$builddir/th06.res",
            "rc",
            inputs="resources/th06.rc",
            implicit="$builddir/icon.ico",
        )
        objfiles = (
            ["$builddir/" + src + ".obj" for src in main_sources]
            + ["$builddir/" + src + ".obj" for src in cxx_sources]
            + ["$builddir/" + src + ".obj" for src in pbg3_sources]
            + ["$builddir/th06.res"]
        )
        if build_type == BuildType.DIFFBUILD:
            objfiles += ["$builddir/globals.obj"]
        writer.build("$builddir/th06e.exe", "link", inputs=objfiles)

        test_objfiles = (
            ["$builddir/" + src + ".obj" for src in cxx_sources]
            + ["$builddir/" + src + ".obj" for src in pbg3_sources]
            + ["$builddir/" + src + ".obj" for src in test_sources]
        )
        writer.build(
            "$builddir/th06e-tests.exe",
            "link",
            inputs=test_objfiles + ["$builddir/munit.lib"],
            variables={
                "link_libs": "$link_libs $builddir/munit.lib",
                "link_flags": "/debug /pdb:$builddir/th06e.pdb",
            },
        )

        writer.build(
            "$builddir/munit.lib",
            "link",
            inputs=["$builddir/" + s + ".obj" for s in munit_sources],
            variables={"link_flags": "/lib", "link_libs": ""},
        )

        writer.close()


if __name__ == "__main__":
    configure(BuildType.NORMAL)
