#!/usr/bin/env bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

PREFIX_PATH=$SCRIPT_DIR/prefix

echo "Creating devenv in $PREFIX_PATH"
# $@ is used to pass all arguments to the python script
python3 "$SCRIPT_DIR/create_devenv.py" "$SCRIPT_DIR/dls" "$PREFIX_PATH" $@

echo "DONE"
