#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
BASE_DIR=$SCRIPT_DIR/..
RESOURCES_DIR=$BASE_DIR/resources
CONFIG_DIR=$BASE_DIR/config

FUNCTION_NAME=$1
echo ".att_syntax"
satsuki --mapping-file $CONFIG_DIR/mapping.toml disassemble --att --force-address-zero $RESOURCES_DIR/game.exe $FUNCTION_NAME
