#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
BASE_DIR=$SCRIPT_DIR/..
BUILD_DIR=$BASE_DIR/build
RESOURCES_DIR=$BASE_DIR/resources
CONFIG_DIR=$BASE_DIR/config
DIFF_DIR=$BASE_DIR/diff

FUNCTION_NAME=$1
FUNCTION_OUTPUT_DIR=$DIFF_DIR/$FUNCTION_NAME

mkdir -p $FUNCTION_OUTPUT_DIR
satsuki --mapping-file $CONFIG_DIR/mapping.toml disassemble --att --force-address-zero $RESOURCES_DIR/game.exe $FUNCTION_NAME > $FUNCTION_OUTPUT_DIR/orig.asm

rm -rf $BUILD_DIR

pushd $BASE_DIR
./scripts/wineth06 scripts/build.bat
popd

satsuki --mapping-file $CONFIG_DIR/mapping.toml disassemble --att --force-address-zero $BUILD_DIR/th06e.exe --pdb-file $BUILD_DIR/th06e.pdb $FUNCTION_NAME > $FUNCTION_OUTPUT_DIR/reimpl.asm
