#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Allow overriding the wine binary used by providing the WINE environment
# variable.
WINE=${WINE:-wine}

export WINEPREFIX=$HOME/.wineth06

MAIN_DRIVE_PATH=$SCRIPT_DIR/prefix
export WINEPATH="$SCRIPT_DIR;$WINEPATH"

# Disable wine logs (comment me for debugging)
export WINEDEBUG=-all
#export LANG=ja_JP.UTF-8

exec $WINE $@ 2> >(grep -v "preloader: Warning: failed to reserve range 0000000000010000-0000000000110000" 1>&2)
