#pragma once

#define ANM_FILE_TEXT 0
#define ANM_FILE_ASCII 1
#define ANM_FILE_ASCIIS 2
#define ANM_FILE_CAPTURE 3
#define ANM_FILE_STAGEBG 4
#define ANM_FILE_PLAYER 5
#define ANM_FILE_BULLET3 6
#define ANM_FILE_BULLET4 7
#define ANM_FILE_ENEMY 8
#define ANM_FILE_ENEMY2 9
#define ANM_FILE_EFFECTS 11
#define ANM_FILE_FRONT 13
#define ANM_FILE_LOADING 14
#define ANM_FILE_FACE_CHARA_A 15
#define ANM_FILE_FACE_CHARA_B 16
#define ANM_FILE_FACE_CHARA_C 17
#define ANM_FILE_FACE_STAGE_A 18
#define ANM_FILE_FACE_STAGE_B 19
#define ANM_FILE_FACE_STAGE_C 20
#define ANM_FILE_TITLE01 21
#define ANM_FILE_TITLE01S 22
#define ANM_FILE_TITLE04S 23
#define ANM_FILE_TITLE02 24
#define ANM_FILE_TITLE03 25
#define ANM_FILE_TITLE04 26
#define ANM_FILE_SELECT01 27
#define ANM_FILE_SELECT02 28
#define ANM_FILE_SELECT03 29
#define ANM_FILE_SELECT04 30
#define ANM_FILE_SELECT05 31
#define ANM_FILE_SLPL00A 32
#define ANM_FILE_SLPL00B 33
#define ANM_FILE_SLPL01A 34
#define ANM_FILE_SLPL01B 35
#define ANM_FILE_REPLAY 36
#define ANM_FILE_RESULT00 37
#define ANM_FILE_RESULT01 38
#define ANM_FILE_RESULT02 39
#define ANM_FILE_RESULT03 40
#define ANM_FILE_MUSIC00 41
#define ANM_FILE_MUSIC01 42
#define ANM_FILE_MUSIC02 43
#define ANM_FILE_STAFF01 44
#define ANM_FILE_STAFF02 45
#define ANM_FILE_STAFF03 46

#define ANM_OFFSET_ASCII 0x000
#define ANM_OFFSET_ASCIIS 0x077
#define ANM_OFFSET_ENEMY 0x100
#define ANM_OFFSET_MUSIC00 0x100
#define ANM_OFFSET_MUSIC01 0x101
#define ANM_OFFSET_MUSIC02 0x111
#define ANM_OFFSET_RESULT00 0x100
#define ANM_OFFSET_RESULT01 0x108
#define ANM_OFFSET_RESULT02 0x10f
#define ANM_OFFSET_RESULT03 0x125
#define ANM_OFFSET_TITLE01 0x100
#define ANM_OFFSET_TITLE02 0x11b
#define ANM_OFFSET_TITLE03 0x11f
#define ANM_OFFSET_TITLE04 0x122
#define ANM_OFFSET_SELECT01 0x150
#define ANM_OFFSET_SELECT02 0x153
#define ANM_OFFSET_SELECT05 0x155
#define ANM_OFFSET_SLPL00A 0x156
#define ANM_OFFSET_SLPL00B 0x157
#define ANM_OFFSET_SLPL01A 0x158
#define ANM_OFFSET_SLPL01B 0x159
#define ANM_OFFSET_SELECT03 0x15a
#define ANM_OFFSET_SELECT04 0x15c
#define ANM_OFFSET_REPLAY 0x160
#define ANM_OFFSET_TITLE01S 0x17a
#define ANM_OFFSET_TITLE04S 0x195
#define ANM_OFFSET_BULLET3 0x200
#define ANM_OFFSET_BULLET4 0x29a
#define ANM_OFFSET_EFFECTS 0x2b3
#define ANM_OFFSET_STAGEBG 0x300
#define ANM_OFFSET_PLAYER 0x400
#define ANM_OFFSET_FACE_CHARA_A 0x4a0
#define ANM_OFFSET_FACE_CHARA_B 0x4a2
#define ANM_OFFSET_FACE_CHARA_C 0x4a4
#define ANM_OFFSET_FACE_STAGE_A 0x4a8
#define ANM_OFFSET_FACE_STAGE_B 0x4aa
#define ANM_OFFSET_FACE_STAGE_C 0x4ab
#define ANM_OFFSET_FRONT 0x600
#define ANM_OFFSET_STAFF01 0x600
#define ANM_OFFSET_STAFF02 0x607
#define ANM_OFFSET_STAFF03 0x60e
#define ANM_OFFSET_LOADING 0x619
#define ANM_OFFSET_TEXT 0x700
#define ANM_OFFSET_CAPTURE 0x718

#define ANM_SPRITE_TITLE01_START ANM_OFFSET_TITLE01
#define ANM_SPRITE_TITLE01_END 0x11a

#define ANM_SPRITE_BULLET3_START ANM_OFFSET_BULLET3
#define ANM_SPRITE_BULLET3_POWER_SMALL (ANM_SPRITE_BULLET3_START + 0)
#define ANM_SPRITE_BULLET3_POINT (ANM_SPRITE_BULLET3_START + 1)
#define ANM_SPRITE_BULLET3_POWER_LARGE (ANM_SPRITE_BULLET3_START + 2)
#define ANM_SPRITE_BULLET3_BOMB (ANM_SPRITE_BULLET3_START + 3)
#define ANM_SPRITE_BULLET3_POWER_FULL (ANM_SPRITE_BULLET3_START + 4)
#define ANM_SPRITE_BULLET3_1UP (ANM_SPRITE_BULLET3_START + 5)
#define ANM_SPRITE_BULLET3_STAR (ANM_SPRITE_BULLET3_START + 6)
#define ANM_SPRITE_BULLET3_PELLET (ANM_SPRITE_BULLET3_START + 14)
#define ANM_SPRITE_BULLET3_RING_BALL (ANM_SPRITE_BULLET3_START + 30)
#define ANM_SPRITE_BULLET3_RICE (ANM_SPRITE_BULLET3_START + 46)
#define ANM_SPRITE_BULLET3_BALL (ANM_SPRITE_BULLET3_START + 62)
#define ANM_SPRITE_BULLET3_KUNAI (ANM_SPRITE_BULLET3_START + 78)
#define ANM_SPRITE_BULLET3_SHARD (ANM_SPRITE_BULLET3_START + 94)
#define ANM_SPRITE_BULLET3_BIG_BALL (ANM_SPRITE_BULLET3_START + 110)
#define ANM_SPRITE_BULLET3_FIREBALL (ANM_SPRITE_BULLET3_START + 118)
#define ANM_SPRITE_BULLET3_DAGGER (ANM_SPRITE_BULLET3_START + 122)
#define ANM_SPRITE_BULLET3_SPAWN_DONUT (ANM_SPRITE_BULLET3_START + 130)
#define ANM_SPRITE_BULLET3_SPAWN_BALL (ANM_SPRITE_BULLET3_START + 135)
#define ANM_SPRITE_BULLET3_SPAWN_BIG_BALL (ANM_SPRITE_BULLET3_START + 140)
#define ANM_SPRITE_BULLET3_LASER (ANM_SPRITE_BULLET3_START + 146)
#define ANM_SPRITE_BULLET3_END 0x299

#define ANM_SPRITE_FACE_CHARA_START ANM_OFFSET_FACE_CHARA_A
#define ANM_SPRITE_FACE_CHARA_END 0x4a5

#define ANM_SPRITE_FACE_STAGE_START ANM_OFFSET_FACE_STAGE_A
#define ANM_SPRITE_FACE_STAGE_END 0x4ab

#define ANM_SPRITE_FACE_START ANM_OFFSET_FACE_STAGE_A

#define ANM_SCRIPT_ASCII_START ANM_OFFSET_ASCII
#define ANM_SCRIPT_ASCII_END 0x009

#define ANM_SCRIPT_ENEMY_START ANM_OFFSET_ENEMY
#define ANM_SCRIPT_ENEMY_END 0x1a5

#define ANM_SCRIPT_RESULT00_START ANM_OFFSET_RESULT00
#define ANM_SCRIPT_RESULT00_END 0x107

#define ANM_SCRIPT_RESULT01_START ANM_OFFSET_RESULT01
#define ANM_SCRIPT_RESULT01_END 0x10e

#define ANM_SCRIPT_RESULT02_START ANM_OFFSET_RESULT02
#define ANM_SCRIPT_RESULT02_END 0x124

#define ANM_SCRIPT_RESULT03_START ANM_OFFSET_RESULT03
#define ANM_SCRIPT_RESULT03_END 0x126

#define ANM_SCRIPT_TITLE01_START ANM_OFFSET_TITLE01
#define ANM_SCRIPT_TITLE01_END 0x11a

#define ANM_SCRIPT_TITLE02_START ANM_OFFSET_TITLE02
#define ANM_SCRIPT_TITLE02_END 0x11e

#define ANM_SCRIPT_TITLE03_START ANM_OFFSET_TITLE03
#define ANM_SCRIPT_TITLE03_END 0x121

#define ANM_SCRIPT_TITLE04_START ANM_OFFSET_TITLE04
#define ANM_SCRIPT_TITLE04_END 0x14f

#define ANM_SCRIPT_SELECT01_START ANM_OFFSET_SELECT01
#define ANM_SCRIPT_SELECT01_END 0x15f

#define ANM_SCRIPT_REPLAY_START ANM_OFFSET_REPLAY
#define ANM_SCRIPT_REPLAY_END 0x179

#define ANM_SCRIPT_BULLET3_START ANM_OFFSET_BULLET3
#define ANM_SCRIPT_BULLET3_PELLET (ANM_SCRIPT_BULLET3_START + 0)
#define ANM_SCRIPT_BULLET3_RING_BALL (ANM_SCRIPT_BULLET3_START + 1)
#define ANM_SCRIPT_BULLET3_RICE (ANM_SCRIPT_BULLET3_START + 2)
#define ANM_SCRIPT_BULLET3_BALL (ANM_SCRIPT_BULLET3_START + 3)
#define ANM_SCRIPT_BULLET3_KUNAI (ANM_SCRIPT_BULLET3_START + 4)
#define ANM_SCRIPT_BULLET3_SHARD (ANM_SCRIPT_BULLET3_START + 5)
#define ANM_SCRIPT_BULLET3_BIG_BALL (ANM_SCRIPT_BULLET3_START + 6)
#define ANM_SCRIPT_BULLET3_FIREBALL (ANM_SCRIPT_BULLET3_START + 7)
#define ANM_SCRIPT_BULLET3_DAGGER (ANM_SCRIPT_BULLET3_START + 8)
#define ANM_SCRIPT_BULLET3_LASER (ANM_SCRIPT_BULLET3_START + 9)
#define ANM_SCRIPT_BULLET3_SPAWN_DONUT_SMALL (ANM_SCRIPT_BULLET3_START + 11)
#define ANM_SCRIPT_BULLET3_SPAWN_DONUT_MEDIUM (ANM_SCRIPT_BULLET3_START + 12)
#define ANM_SCRIPT_BULLET3_SPAWN_DONUT_BIG (ANM_SCRIPT_BULLET3_START + 13)
#define ANM_SCRIPT_BULLET3_SPAWN_PELLET_FAST (ANM_SCRIPT_BULLET3_START + 14)
#define ANM_SCRIPT_BULLET3_SPAWN_PELLET_NORMAL (ANM_SCRIPT_BULLET3_START + 15)
#define ANM_SCRIPT_BULLET3_SPAWN_PELLET_SLOW (ANM_SCRIPT_BULLET3_START + 16)
#define ANM_SCRIPT_BULLET3_SPAWN_BIG_BALL_FAST (ANM_SCRIPT_BULLET3_START + 17)
#define ANM_SCRIPT_BULLET3_SPAWN_BIG_BALL_NORMAL (ANM_SCRIPT_BULLET3_START + 18)
#define ANM_SCRIPT_BULLET3_SPAWN_BIG_BALL_SLOW (ANM_SCRIPT_BULLET3_START + 19)
#define ANM_SCRIPT_BULLET3_SPAWN_BIG_BALL_HUGE (ANM_SCRIPT_BULLET3_START + 20)
#define ANM_SCRIPT_BULLET3_ITEMS_START (ANM_SCRIPT_BULLET3_START + 21)
#define ANM_SCRIPT_BULLET3_END 0x21b

#define ANM_SCRIPT_BULLET4_START ANM_OFFSET_BULLET4
#define ANM_SCRIPT_BULLET4_BUBBLE (ANM_SCRIPT_BULLET4_START + 0)
#define ANM_SCRIPT_BULLET4_SPAWN_BUBBLE_NORMAL (ANM_SCRIPT_BULLET4_START + 1)
#define ANM_SCRIPT_BULLET4_SPAWN_BUBBLE_SLOW (ANM_SCRIPT_BULLET4_START + 2)
#define ANM_SCRIPT_BULLET4_SPAWN_BUBBLE_EXPLOSION_SMALL (ANM_SCRIPT_BULLET4_START + 3)
#define ANM_SCRIPT_BULLET4_SPAWN_BUBBLE_EXPLOSION_SPIRAL (ANM_SCRIPT_BULLET4_START + 4)
#define ANM_SCRIPT_BULLET4_SPAWN_BUBBLE_EXPLOSION_NORMAL (ANM_SCRIPT_BULLET4_START + 5)
#define ANM_SCRIPT_BULLET4_SPAWN_GLOW_1 (ANM_SCRIPT_BULLET4_START + 6)
#define ANM_SCRIPT_BULLET4_SPAWN_GLOW_2 (ANM_SCRIPT_BULLET4_START + 7)
#define ANM_SCRIPT_BULLET4_SPAWN_GLOW_3 (ANM_SCRIPT_BULLET4_START + 8)
#define ANM_SCRIPT_BULLET4_SPAWN_WHITE_PARTICLE (ANM_SCRIPT_BULLET4_START + 9)
#define ANM_SCRIPT_BULLET4_SPAWN_RED_PARTICLE (ANM_SCRIPT_BULLET4_START + 10)
#define ANM_SCRIPT_BULLET4_SPAWN_GREEN_PARTICLE (ANM_SCRIPT_BULLET4_START + 11)
#define ANM_SCRIPT_BULLET4_SPAWN_BLUE_PARTICLE (ANM_SCRIPT_BULLET4_START + 12)
#define ANM_SCRIPT_BULLET4_SPAWN_WHITE_PARTICLE_SMALL (ANM_SCRIPT_BULLET4_START + 13)
#define ANM_SCRIPT_BULLET4_SPAWN_RED_PARTICLE_SMALL (ANM_SCRIPT_BULLET4_START + 14)
#define ANM_SCRIPT_BULLET4_SPAWN_GREEN_PARTICLE_SMALL (ANM_SCRIPT_BULLET4_START + 15)
#define ANM_SCRIPT_BULLET4_SPAWN_BLUE_PARTICLE_SMALL (ANM_SCRIPT_BULLET4_START + 16)
#define ANM_SCRIPT_BULLET4_SCRIPT_17 (ANM_SCRIPT_BULLET4_START + 17)
#define ANM_SCRIPT_BULLET4_SCRIPT_18 (ANM_SCRIPT_BULLET4_START + 18)
#define ANM_SCRIPT_BULLET4_SCRIPT_19 (ANM_SCRIPT_BULLET4_START + 19)
#define ANM_SCRIPT_BULLET4_SCRIPT_20 (ANM_SCRIPT_BULLET4_START + 20)
#define ANM_SCRIPT_BULLET4_END 0x2ae

#define ANM_SCRIPT_EFFECTS_START ANM_OFFSET_EFFECTS
#define ANM_SCRIPT_EFFECTS_SPELLCARD_BACKGROUND (ANM_SCRIPT_EFFECTS_START + 0)
#define ANM_SCRIPT_EFFECTS_END 0x2b3

#define ANM_SCRIPT_PLAYER_START ANM_OFFSET_PLAYER
#define ANM_SCRIPT_PLAYER_IDLE (ANM_SCRIPT_PLAYER_START + 0)
#define ANM_SCRIPT_PLAYER_MOVING_LEFT (ANM_SCRIPT_PLAYER_START + 1)
#define ANM_SCRIPT_PLAYER_STOPPING_LEFT (ANM_SCRIPT_PLAYER_START + 2)
#define ANM_SCRIPT_PLAYER_MOVING_RIGHT (ANM_SCRIPT_PLAYER_START + 3)
#define ANM_SCRIPT_PLAYER_STOPPING_RIGHT (ANM_SCRIPT_PLAYER_START + 4)
#define ANM_SCRIPT_PLAYER_MARISA_A_BLUE_STAR (ANM_SCRIPT_PLAYER_START + 5)
#define ANM_SCRIPT_PLAYER_MARISA_A_GREEN_STAR (ANM_SCRIPT_PLAYER_START + 6)
#define ANM_SCRIPT_PLAYER_MARISA_A_RED_STAR (ANM_SCRIPT_PLAYER_START + 7)
#define ANM_SCRIPT_PLAYER_MARISA_B_MASTER_SPARK (ANM_SCRIPT_PLAYER_START + 8)
#define ANM_SCRIPT_PLAYER_BULLET (ANM_SCRIPT_PLAYER_START + 64)
#define ANM_SCRIPT_PLAYER_REIMU_A_ORB_BULLET (ANM_SCRIPT_PLAYER_START + 65)
#define ANM_SCRIPT_PLAYER_REIMU_B_ORB_BULLET (ANM_SCRIPT_PLAYER_START + 66)
#define ANM_SCRIPT_PLAYER_REIMU_BULLET_COLLISION (ANM_SCRIPT_PLAYER_START + 96)
#define ANM_SCRIPT_PLAYER_REIMU_A_ORB_BULLET_COLLISION (ANM_SCRIPT_PLAYER_START + 97)
#define ANM_SCRIPT_PLAYER_REIMU_B_ORB_BULLET_COLLISION (ANM_SCRIPT_PLAYER_START + 98)
#define ANM_SCRIPT_PLAYER_MARISA_A_ORB_BULLET_1 (ANM_SCRIPT_PLAYER_START + 65)
#define ANM_SCRIPT_PLAYER_MARISA_A_ORB_BULLET_2 (ANM_SCRIPT_PLAYER_START + 66)
#define ANM_SCRIPT_PLAYER_MARISA_A_ORB_BULLET_3 (ANM_SCRIPT_PLAYER_START + 67)
#define ANM_SCRIPT_PLAYER_MARISA_A_ORB_BULLET_4 (ANM_SCRIPT_PLAYER_START + 68)
#define ANM_SCRIPT_PLAYER_MARISA_B_ORB_LASER_1 (ANM_SCRIPT_PLAYER_START + 69)
#define ANM_SCRIPT_PLAYER_MARISA_B_ORB_LASER_2 (ANM_SCRIPT_PLAYER_START + 70)
#define ANM_SCRIPT_PLAYER_MARISA_B_ORB_LASER_3 (ANM_SCRIPT_PLAYER_START + 71)
#define ANM_SCRIPT_PLAYER_MARISA_BULLET_COLLISION (ANM_SCRIPT_PLAYER_START + 96)
#define ANM_SCRIPT_PLAYER_MARISA_A_ORB_BULLET_COLLISION_1 (ANM_SCRIPT_PLAYER_START + 97)
#define ANM_SCRIPT_PLAYER_MARISA_A_ORB_BULLET_COLLISION_2 (ANM_SCRIPT_PLAYER_START + 98)
#define ANM_SCRIPT_PLAYER_MARISA_A_ORB_BULLET_COLLISION_3 (ANM_SCRIPT_PLAYER_START + 99)
#define ANM_SCRIPT_PLAYER_MARISA_A_ORB_BULLET_COLLISION_4 (ANM_SCRIPT_PLAYER_START + 100)
#define ANM_SCRIPT_PLAYER_ORB_LEFT (ANM_SCRIPT_PLAYER_START + 128)
#define ANM_SCRIPT_PLAYER_ORB_RIGHT (ANM_SCRIPT_PLAYER_START + 129)
#define ANM_SCRIPT_PLAYER_REIMU_A_BOMB_ARRAY (ANM_SCRIPT_PLAYER_START + 133)
#define ANM_SCRIPT_PLAYER_REIMU_B_BOMB_ARRAY (ANM_SCRIPT_PLAYER_START + 137)
#define ANM_SCRIPT_PLAYER_END 0x48c

#define ANM_SCRIPT_FACE_START ANM_OFFSET_FACE_CHARA_A
#define ANM_SCRIPT_FACE_BOMB_PORTRAIT (ANM_SCRIPT_FACE_START + 1)
#define ANM_SCRIPT_FACE_ENEMY_SPELLCARD_PORTRAIT (ANM_SCRIPT_FACE_START + 3)
#define ANM_SCRIPT_FACE_END 0x4a3

#define ANM_SCRIPT_FRONT_START ANM_OFFSET_FRONT
#define ANM_SCRIPT_FRONT_ENEMY_TEXT (ANM_SCRIPT_FRONT_START + 19)
#define ANM_SCRIPT_FRONT_ENEMY_TEXT2 (ANM_SCRIPT_FRONT_START + 20)
#define ANM_SCRIPT_FRONT_BOMB_NAME_BACKGROUND (ANM_SCRIPT_FRONT_START + 23)
#define ANM_SCRIPT_FRONT_ENEMY_SPELLCARD_BACKGROUND (ANM_SCRIPT_FRONT_START + 24)
#define ANM_SCRIPT_FRONT_END 0x618

#define ANM_SCRIPT_LOADING_START ANM_OFFSET_LOADING
#define ANM_SCRIPT_LOADING_SHOW_LOADING_SCREEN (ANM_SCRIPT_LOADING_START + 0)
#define ANM_SCRIPT_LOADING_END 0x619

#define ANM_SCRIPT_TEXT_START ANM_OFFSET_TEXT
#define ANM_SCRIPT_TEXT_STAGE_NAME (ANM_SCRIPT_TEXT_START + 0)
#define ANM_SCRIPT_TEXT_SONG_NAME (ANM_SCRIPT_TEXT_START + 1)
#define ANM_SCRIPT_TEXT_BOMB_NAME (ANM_SCRIPT_TEXT_START + 6)
#define ANM_SCRIPT_TEXT_ENEMY_SPELLCARD_NAME (ANM_SCRIPT_TEXT_START + 7)
#define ANM_SCRIPT_TEXT_RESULTSCREEN_CHARACTER_NAME (ANM_SCRIPT_TEXT_START + 8)
#define ANM_SCRIPT_TEXT_ENDING_TEXT (ANM_SCRIPT_TEXT_START + 8)
#define ANM_SCRIPT_TEXT_MUSIC_ROOM_DESC (ANM_SCRIPT_TEXT_START + 8)
#define ANM_SCRIPT_TEXT_END 0x717

#define ANM_SCRIPT_CAPTURE_START ANM_OFFSET_CAPTURE
#define ANM_SCRIPT_CAPTURE_PAUSE_BG (ANM_SCRIPT_CAPTURE_START + 0)
#define ANM_SCRIPT_CAPTURE_END 0x718
