#pragma once

#define ANM_FILE_TEXT 0
#define ANM_FILE_ASCII 1
#define ANM_FILE_ASCIIS 2
#define ANM_FILE_CAPTURE 3
#define ANM_FILE_PLAYER 5
#define ANM_FILE_BULLET3 6
#define ANM_FILE_BULLET4 7
#define ANM_FILE_ENEMY 8
#define ANM_FILE_ENEMY2 9
#define ANM_FILE_EFFECTS 11
#define ANM_FILE_FRONT 13
#define ANM_FILE_LOADING 14
#define ANM_FILE_FACE_CHARA_A 15
#define ANM_FILE_FACE_CHARA_B 16
#define ANM_FILE_FACE_CHARA_C 17
#define ANM_FILE_FACE_STAGE_A 18
#define ANM_FILE_FACE_STAGE_B 19
#define ANM_FILE_FACE_STAGE_C 20
#define ANM_FILE_TITLE01 21
#define ANM_FILE_TITLE01S 22
#define ANM_FILE_TITLE04S 23
#define ANM_FILE_TITLE02 24
#define ANM_FILE_TITLE03 25
#define ANM_FILE_TITLE04 26
#define ANM_FILE_SELECT01 27
#define ANM_FILE_SELECT02 28
#define ANM_FILE_SELECT03 29
#define ANM_FILE_SELECT04 30
#define ANM_FILE_SELECT05 31
#define ANM_FILE_SLPL00A 32
#define ANM_FILE_SLPL00B 33
#define ANM_FILE_SLPL01A 34
#define ANM_FILE_SLPL01B 35
#define ANM_FILE_REPLAY 36

#define ANM_OFFSET_ASCII 0x000
#define ANM_OFFSET_ASCIIS 0x077
#define ANM_OFFSET_ENEMY 0x100
#define ANM_OFFSET_TITLE01 0x100
#define ANM_OFFSET_TITLE02 0x11b
#define ANM_OFFSET_TITLE03 0x11f
#define ANM_OFFSET_TITLE04 0x122
#define ANM_OFFSET_SELECT01 0x150
#define ANM_OFFSET_SELECT02 0x153
#define ANM_OFFSET_SELECT05 0x155
#define ANM_OFFSET_SLPL00A 0x156
#define ANM_OFFSET_SLPL00B 0x157
#define ANM_OFFSET_SLPL01A 0x158
#define ANM_OFFSET_SLPL01B 0x159
#define ANM_OFFSET_SELECT03 0x15a
#define ANM_OFFSET_SELECT04 0x15c
#define ANM_OFFSET_REPLAY 0x160
#define ANM_OFFSET_TITLE01S 0x17a
#define ANM_OFFSET_TITLE04S 0x195
#define ANM_OFFSET_BULLET3 0x200
#define ANM_OFFSET_BULLET4 0x29a
#define ANM_OFFSET_EFFECTS 0x2b3
#define ANM_OFFSET_PLAYER 0x400
#define ANM_OFFSET_FACE_CHARA_A 0x4a0
#define ANM_OFFSET_FACE_CHARA_B 0x4a2
#define ANM_OFFSET_FACE_CHARA_C 0x4a4
#define ANM_OFFSET_FACE_STAGE_A 0x4a8
#define ANM_OFFSET_FACE_STAGE_B 0x4aa
#define ANM_OFFSET_FACE_STAGE_C 0x4ab
#define ANM_OFFSET_FRONT 0x600
#define ANM_OFFSET_LOADING 0x619
#define ANM_OFFSET_TEXT 0x700
#define ANM_OFFSET_CAPTURE 0x718

#define ANM_SPRITE_TITLE01_START ANM_OFFSET_TITLE01
#define ANM_SPRITE_TITLE01_END 0x11a

#define ANM_SCRIPT_ASCII_START ANM_OFFSET_ASCII
#define ANM_SCRIPT_ASCII_END 0x009

#define ANM_SCRIPT_ENEMY_START ANM_OFFSET_ENEMY
#define ANM_SCRIPT_ENEMY_END 0x1a5

#define ANM_SCRIPT_TITLE01_START ANM_OFFSET_TITLE01
#define ANM_SCRIPT_TITLE01_END 0x11a

#define ANM_SCRIPT_TITLE02_START ANM_OFFSET_TITLE02
#define ANM_SCRIPT_TITLE02_END 0x11e

#define ANM_SCRIPT_TITLE03_START ANM_OFFSET_TITLE03
#define ANM_SCRIPT_TITLE03_END 0x121

#define ANM_SCRIPT_TITLE04_START ANM_OFFSET_TITLE04
#define ANM_SCRIPT_TITLE04_END 0x14f

#define ANM_SCRIPT_REPLAY_START ANM_OFFSET_REPLAY
#define ANM_SCRIPT_REPLAY_END 0x179

#define ANM_SCRIPT_BULLET3_START ANM_OFFSET_BULLET3
#define ANM_SCRIPT_BULLET3_PELLET (ANM_SCRIPT_BULLET3_START + 0)
#define ANM_SCRIPT_BULLET3_RING_BALL (ANM_SCRIPT_BULLET3_START + 1)
#define ANM_SCRIPT_BULLET3_RICE (ANM_SCRIPT_BULLET3_START + 2)
#define ANM_SCRIPT_BULLET3_BALL (ANM_SCRIPT_BULLET3_START + 3)
#define ANM_SCRIPT_BULLET3_KUNAI (ANM_SCRIPT_BULLET3_START + 4)
#define ANM_SCRIPT_BULLET3_SHARD (ANM_SCRIPT_BULLET3_START + 5)
#define ANM_SCRIPT_BULLET3_BIG_BALL (ANM_SCRIPT_BULLET3_START + 6)
#define ANM_SCRIPT_BULLET3_FIREBALL (ANM_SCRIPT_BULLET3_START + 7)
#define ANM_SCRIPT_BULLET3_DAGGER (ANM_SCRIPT_BULLET3_START + 8)
#define ANM_SCRIPT_BULLET3_SPAWN_DONUT_SMALL (ANM_SCRIPT_BULLET3_START + 11)
#define ANM_SCRIPT_BULLET3_SPAWN_DONUT_MEDIUM (ANM_SCRIPT_BULLET3_START + 12)
#define ANM_SCRIPT_BULLET3_SPAWN_DONUT_BIG (ANM_SCRIPT_BULLET3_START + 13)
#define ANM_SCRIPT_BULLET3_SPAWN_PELLET_FAST (ANM_SCRIPT_BULLET3_START + 14)
#define ANM_SCRIPT_BULLET3_SPAWN_PELLET_NORMAL (ANM_SCRIPT_BULLET3_START + 15)
#define ANM_SCRIPT_BULLET3_SPAWN_PELLET_SLOW (ANM_SCRIPT_BULLET3_START + 16)
#define ANM_SCRIPT_BULLET3_SPAWN_BIG_BALL_FAST (ANM_SCRIPT_BULLET3_START + 17)
#define ANM_SCRIPT_BULLET3_SPAWN_BIG_BALL_NORMAL (ANM_SCRIPT_BULLET3_START + 18)
#define ANM_SCRIPT_BULLET3_SPAWN_BIG_BALL_SLOW (ANM_SCRIPT_BULLET3_START + 19)
#define ANM_SCRIPT_BULLET3_SPAWN_BIG_BALL_HUGE (ANM_SCRIPT_BULLET3_START + 20)
#define ANM_SCRIPT_BULLET3_END 0x21b

#define ANM_SCRIPT_BULLET4_START ANM_OFFSET_BULLET4
#define ANM_SCRIPT_BULLET4_BUBBLE (ANM_SCRIPT_BULLET4_START + 0)
#define ANM_SCRIPT_BULLET4_SPAWN_BUBBLE_NORMAL (ANM_SCRIPT_BULLET4_START + 1)
#define ANM_SCRIPT_BULLET4_SPAWN_BUBBLE_SLOW (ANM_SCRIPT_BULLET4_START + 2)
#define ANM_SCRIPT_BULLET4_END 0x2ae

#define ANM_SCRIPT_EFFECTS_START ANM_OFFSET_EFFECTS
#define ANM_SCRIPT_EFFECTS_END 0x2b3

#define ANM_SCRIPT_PLAYER_START ANM_OFFSET_PLAYER
#define ANM_SCRIPT_PLAYER_IDLE (ANM_SCRIPT_PLAYER_START + 0)
#define ANM_SCRIPT_PLAYER_ORB_LEFT (ANM_SCRIPT_PLAYER_START + 128)
#define ANM_SCRIPT_PLAYER_ORB_RIGHT (ANM_SCRIPT_PLAYER_START + 129)
#define ANM_SCRIPT_PLAYER_END 0x48c

#define ANM_SCRIPT_FACE_START ANM_OFFSET_FACE_CHARA_A
#define ANM_SCRIPT_FACE_BOMB_PORTRAIT (ANM_SCRIPT_FACE_START + 1)
#define ANM_SCRIPT_FACE_ENEMY_SPELLCARD_PORTRAIT (ANM_SCRIPT_FACE_START + 3)
#define ANM_SCRIPT_FACE_END 0x4a3

#define ANM_SCRIPT_FRONT_START ANM_OFFSET_FRONT
#define ANM_SCRIPT_FRONT_BOMB_NAME_BACKGROUND (ANM_SCRIPT_FRONT_START + 23)
#define ANM_SCRIPT_FRONT_ENEMY_SPELLCARD_BACKGROUND (ANM_SCRIPT_FRONT_START + 24)
#define ANM_SCRIPT_FRONT_END 0x618

#define ANM_SCRIPT_LOADING_START ANM_OFFSET_LOADING
#define ANM_SCRIPT_LOADING_SHOW_LOADING_SCREEN (ANM_SCRIPT_LOADING_START + 0)
#define ANM_SCRIPT_LOADING_END 0x619

#define ANM_SCRIPT_TEXT_START ANM_OFFSET_TEXT
#define ANM_SCRIPT_TEXT_STAGE_NAME (ANM_SCRIPT_TEXT_START + 0)
#define ANM_SCRIPT_TEXT_SONG_NAME (ANM_SCRIPT_TEXT_START + 1)
#define ANM_SCRIPT_TEXT_BOMB_NAME (ANM_SCRIPT_TEXT_START + 6)
#define ANM_SCRIPT_TEXT_ENEMY_SPELLCARD_NAME (ANM_SCRIPT_TEXT_START + 7)
#define ANM_SCRIPT_TEXT_END 0x717

#define ANM_SCRIPT_CAPTURE_START ANM_OFFSET_CAPTURE
#define ANM_SCRIPT_CAPTURE_END 0x718
