#pragma once

#define TH_CHAIN_PRIO_CALC_SUPERVISOR 0
#define TH_CHAIN_PRIO_CALC_ASCIIMANAGER 1

#define TH_CHAIN_PRIO_DRAW_ASCIIMANAGER_POPUPS 10
#define TH_CHAIN_PRIO_DRAW_SUPERVISOR 14
#define TH_CHAIN_PRIO_DRAW_ASCIIMANAGER_MENUS 15
