#pragma once

#define TH_CHAIN_PRIO_CALC_SUPERVISOR 0
#define TH_CHAIN_PRIO_CALC_ASCIIMANAGER 1
#define TH_CHAIN_PRIO_CALC_MAINMENU 2
#define TH_CHAIN_PRIO_CALC_GAMEMANAGER 4
#define TH_CHAIN_PRIO_CALC_STAGE 6

#define TH_CHAIN_PRIO_DRAW_MAINMENU 0
#define TH_CHAIN_PRIO_DRAW_GAMEMANAGER 2
#define TH_CHAIN_PRIO_DRAW_HIGH_PRIO_STAGE 3
#define TH_CHAIN_PRIO_DRAW_LOW_PRIO_STAGE 4
#define TH_CHAIN_PRIO_DRAW_ASCIIMANAGER_POPUPS 10
#define TH_CHAIN_PRIO_DRAW_SUPERVISOR 14
#define TH_CHAIN_PRIO_DRAW_ASCIIMANAGER_MENUS 15
