#include "th06.hpp"
#include <stdio.h>

namespace th06
{

// These stubs are auto-generated by generate_stubs.py based on the contents of
// config/stubbed.csv
#include "auto_stubbed.cpp"
}; // namespace th06
