#include "AnmManager.hpp"
#include "AsciiManager.hpp"
#include "Chain.hpp"
#include "GameWindow.hpp"
#include "MidiOutput.hpp"
#include "SoundPlayer.hpp"
#include "Supervisor.hpp"
#include "inttypes.hpp"

// These stubs are auto-generated by generate_stubs.py based on the contents of
// config/stubbed.csv
#include "auto_stubbed.cpp"
